

catalogue:
		@bash components/catalogue.sh
mongodb:
		@bash components/mongodb.sh
		
redis:
		@bash components/radis.sh
user:
		@bash components/user.sh
cart:
		@bash components/cart.sh
mysql:
		@bash components/mysql.sh
shipping:
		@bash components/shipping.sh
rabbitmq:
		@bash components/mbabbitmq.sh
payment:
		@bash components/payment.sh
frontend:
		@bash components/frontend.sh		
		